language: java
# sudo: true
# dist: trusty
jdk: openjdk11
before_install:
  - chmod +x mvnw
services:
  - mongodb

addons:
  sonarcloud:
    organization: "pusl-tud"
    token:
      secure: "hO+dWyRrtcNcwjh8x/k2XJfw5nTYCApEXSwE3UdFfU1I53quY89hFVbLhBIcD3V84zLcyO+FrSEQnNILtumTdRBxC5525TpSnmhM09oY7w9ZfS4dRTkuzj5C3ekqixLbN9k+XVQp5VZvTrR6Bijgc9hZVtv0B7Ce9XH+60jG2fxojydXBnAcWnFMRVXSBe/+NhHcgQHG1jkqsOYFDft0K7VE8kSb+YR2YCCwgwxQhc6gYmY51mC4iSDYhOgMej0MPAWHBdjHM7/3/K/CrapydxDzih+M+VhtnZfWXXJa1jPvo28QZ9CYxkP/o3zrNEUjIq1nhy1V+Qqd3OWhM2gAiUZQxFqPJEsaYUbDO/wOzl8mGVrDjbk4lrbA14Y+KuWCz2YSdV9y4hPcdap+H1Zrv35d8j4UIEfjxWo+FAEngpe6qRydut3F1yi/6EHMIyXn1so8n9wAT4lApbwD6pOBeICqf6rbUY4E7D0B50f4DtlE9NJJSiG9BoATnXsAnWGAsOBtgql9pWupLjh+A8BXHbchkkyQ3dLs3Ru3T09dtWcQfsveBIpWNyc0A3l/z6iiPKcPh6plcjhpOf1k2JHRuLlDwzcQHQZxyxByFFgaFN4iEP0CLzvR4eRcoLyQEfDeHkHlAWPg8L24nqJMJddK0TVFeXhLA0+ieyrd6y3xTEY="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar