language: java
os: linux
dist: xenial
jdk: openjdk11
before_install:
  - chmod +x mvnw
services:
  - mongodb

addons:
  sonarcloud:
    organization: "pusl-tud"
    token:
      secure: "GKU5cxwbtmbp5ZTy5TrINj3HVWJZQSrEjphGfmXisrBA1pyEHe/joOiL3JoxeKFf5pus/NzWegp4PzNyJPEEzt5MLnOId4/HSvr5+N+Jm0YkJvYy0hMrkUqU4R8A3LFMQIEyVsYrFe9f5LAklTODBsGChEm1IHA29klTud1htr/8Fmh6WNyJEL7VqsVsaO2BFj6gvGqkuGfZaUPn3M4G2UhF4f9ryTiBgdr3qDUmxmgVRyjp2tCNQPUGOFYt0RVrqhldjZe5I8ANGJnRhlTzE8FKk/Zjwd/y0wRjzU0GPSVXwrNZorS73fquTpYSNry1w2g6H+I18xTwbxHB2AQ+CVuIDMjYW6qw+dzOW+/cZxjnpTE0k1Uw1SbE9AoFzDdTfQXRvxQLR2ubyrdyFtZs3EU+S7MBwISFK+7mrg7EdWyG24RWbguw7WHCeik0TYDN6squK5P82t0orh46jqx58LNY82H+Z6RrqyFcQWXd1N5oxB0CL+VlBkZc+af9F/j43HZGY/8gtUKd7bIw0RqKdh2ThGNGvZRlkFWwpAZFLi0258AaHCV/Pma9ptjrnwnmJOk5Vhi7gv/WiiaDgvdaIdaUOPXs5HRaNgvVAzIQ+oYVW/AL9bktLYSgh0BMiBKDFWZMWsaNXE770Kzv4y+CFi9t6OpmHYU0kP+i5tAiuNM="

script:
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean install